JeffersonLab/japan

Analysis/src/QwF1TDContainer.cc
Since both reference_trig_time and fF1TDCDecoder.GetTDCHeaderTriggerTime()
return a UInt_t and taking the difference is going to return a UInt_t as
well, we should convert to Long_t first. Then the std::abs is well defined
and doesn't fail to compile on gcc-8.
=> Convert UInt_t to Long_t before taking difference and abs. Fixes #34.

Parity/src/QwComptonElectronDetector.cc, evio/include/THaCodaFile.h, evio/include/THaEtClient.h, evio/src/THaCodaFile.C
There are potential issues with `using namespace std`, in particular
in header files like `THa*.h`. Functions like std::abs() can be called
simply as abs() which may cause confusion when another header defines
abs().
More detailed reasons:
https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice
=> Avoid `using namespace std` by specifying std:: when needed.

Analysis/src/QwOptions.cc, Analysis/src/QwRunCondition.cc, Parity/src/LRBCorrector.cc, Parity/src/QwCorrelator.cc, bin/pullgitinfo.py
Minor change, but increases readability and maintainability.
=> Use string literal gitinfo instead of hex-encoded version

Analysis/include/QwEventBuffer.h, Analysis/include/QwOptions.h, Analysis/src/QwOptions.cc, Parity/main/QwParity.cc, Parity/prminput/online_apar.conf
This should be the last thing needed to demonstrate we have completed issue #16.
To test the functionality of connecting to the 2ET system, you need to be on apar@adaq3, then:
1)  Start coda and start a run
2)  Execute `./build/qwparity --config prex.conf --add-config online_apar.conf `.  This should connect to the ET system and you should see helicity event processing messages for the first 30 patterns.  The event processing rate should match the CODA rate.
3)  In the ROOT file directory, a file `prexALL_0.root` should be created and its size should be growing.
4)  Use ctrl-C to stop the analysis process.  The rootfile should remain, and should contain the usual trees, if you inspect the contents.
=> Bugfix online epicscheck

Parity/prminput/simulate_online_disk_file.conf
Turn off circular buffer to allow for faster online analyzer running
=> Turn off circular buffer to allow for faster

Parity/prminput/prexCH_beamline_eventcuts.1329-.map, Parity/prminput/prexCH_beamline_eventcuts.map, Parity/src/QwEventRing.cc
Previously (see discussion in issue #92) the stability cut was only
evaluated when we reached the end of the event ring.  Now the stability
cut will be evaluated as each event is pushed into the ring.
This improves the detection of beam trips.
However, there's still an issue with recognizing the start of the
beam trip and really cutting a full "ring.size" events before the trip.
This version does definitely cut away before the beam trips, but it
is fewer events than it ought to be.
The next stage should refactor how we do the stability check so that
we look at the width and at the values of the event which is being
pushed into the ring.  A failed single-event cut on a channel we are
monitoring stability should also trigger the stability cut.
Possibly a single-event change which is "large" …
=> Modified the stability cut functionality.

Parity/include/QwBlinder.h, Parity/include/QwHelicityPattern.h, Parity/main/QwParity.cc, Parity/src/QwBlinder.cc, Parity/src/QwHelicity.cc, Parity/src/QwHelicityPattern.cc
Each sequential pair of events in a pattern will have a pair yield and asymmetry calculated.  The pair based results will go into a pair tree, called "pr".  When the "print-runningsum" flag is present, the pair running sums will be printed after the pattern running sums.
This resolves issues #93 and #65.  Note to get the helicity independent asymmetries ((1-2)/(1+2)) from the "pr" tree, the asymmetry leaf should be multiplied by "(2*actual_helicity-1)" which will be  the sign of the first event of the pair:  actual_helicity==1 for Hel+ as the first event, and actual_helicity==0 for Hel- as the first event.
The "actual_helicity" variable in the mul tree is not useful, as it represents the helicity of the first Hel+ event in the pattern, so it is always 1.  The realtive polarity of the …
=> Feature pairanalysis

Analysis/include/QwEventBuffer.h, Analysis/src/QwEventBuffer.cc, Analysis/src/QwOptions.cc
QwEventBuffer is the only class using $QW_DATA env var support. Now we
have a static default data directory ("/adaq1/data1/apar") which is
overriden by QW_DATA or -d/--data.
QwOptions was slightly modified in its env var parsing. Instead of
requiring a prefix "Qw" (i.e. Qwrun=100 is equivalent to --run=100) it
now uses "QW_" as prefix.
Unfortunately boost::program_options::parse_environment does not allow
for the "allow_unregistered()" decorator, so we immediately trip up over
the unparsed $QW_FIELDMAP and the like. We bypass this problem by
writing a functor to which we can specify a set of lowercase appendages
to ignore (e.g. "fieldmap"). The rest the functor does it stripping the
prefix "QW_" and turning the rest to lowercase for parsing "QW_DATA" as
"data" and then recognizing as the …
=> Implemented options -d/--data for $QW_DATA support

Parity/include/QwIntegrationPMT.h, Parity/src/QwDetectorArray.cc, Parity/src/QwIntegrationPMT.cc
Optional parameter for setting saturation limit to integration PMTs.
By default, the 8.5 volt limit is initialized by QwVQWK_Channel constructor [Line 66 ](https://github.com/JeffersonLab/japan/blob/cdd64b4dc958b722b001ca87d451e3791bbec190/Analysis/include/QwVQWK_Channel.h#L66).
The new parameter will overwrite the default value if it is specified in the detector map.
=> Added a new config parameter saturation limit for integration PMT

Analysis/include/QwOptions.h, Analysis/src/QwOptions.cc
gQwOptions is now a preprocessor define for QwOptions::Instance() which
avoids any code changes in other classes (even if it does something
different on the back end). The non-default constructors for QwOptions
were removed since unused. Static fArgc, fArgv were removed since now
inside the static member of the singleton pattern.
The main reason for this change is to make the QwOptions implementation cleaner.
=> Make QwOptions a singleton class

Analysis/include/QwRootFile.h, Analysis/src/QwPromptSummary.cc, Analysis/src/QwRootFile.cc
Now `qwparity --rootfiles <dir>` is (or should be) equivalent to `QW_ROOTFILES=<dir> qwparity`. The default rootfiles directory is `.` but even that can be changed (before defining the QwRootFile option) by calling QwRootFile::SetDefaultRootFileDir().
Removed QW_ROOTFILES_LOCAL since not necessary if this environment
variable can be overridden in many several ways now (in qwparity.conf
and on command line, in that order of override power).
QwPromptSummary uses QW_ROOTFILES and should pick up the right value too.
=> Changed QW_ROOTFILES into QwOptions variable

panguin/panguin.cc
This way we do not depend upon the root macro search path being defined properly in the .rootrc file.
=> Explicitly add the panguin "macros" subdirectory to the gROOT macro search path

Analysis/include/QwRootFile.h, Analysis/include/QwSubsystemArray.h, Analysis/include/VQwSubsystem.h, Analysis/src/QwSubsystemArray.cc, Parity/include/QwBlinder.h, Parity/include/QwHelicityPattern.h, Parity/main/QwParity_simple.cc, Parity/src/QwHelicityPattern.cc
In similar vein (and maybe in vain too) to the `ConstructHistograms` and `ConstructBranchAndTreeVector` this provides another interface to the ROOT file, but it is only supposed to be called once. Probably that means at the beginning or at the end of the ROOT file, depending on what you use it for (beginning if you write configuration and want to ensure data is saved also when run crashes; end if you write summary information for the entire run, like running sums etc).
Possible modifications:
=> Feature: set of ConstructObjects methods to store arbitrary TObjects once

rootScripts/aggregator/camAna.hh, rootScripts/aggregator/camHist.hh, rootScripts/aggregator/camIO.hh, rootScripts/aggregator/camguin.C, rootScripts/aggregator/regressor/camReg.hh, rootScripts/aggregator/regressor/camRegDipole.hh, rootScripts/aggregator/setup_camguin.tcsh
Adding file split handling (to all methods and to agg rootfile printing/editing)
Making loop and histogram Cut mechanics more consistent and correct
Making WeightedHistogram fail safely in Integral method
Adding a feature to compute the starting event number that survives cuts
and goes for a specified length - effectively creating an event loop
feature. The user specifies the length N and the Cut/loop feature finds
which event number starts the loop that contains N cut-passing events
and which ends on the final event in the tree (first step to making
an alarm handler work on live data).
=> This satisfies the request to have the IO utilize file splits correctly

Parity/src/QwCorrelator.cc, Parity/src/QwkRegBlueCorrelator.cc
Previously not loadable since function name start with slash, no
return type, uses undefined locals.
Now proper void, no slash, gets "mul" from current directory of
ROOT file i.e. loads `.x regalias_1296.C` works now.
Does anyone use this file? If not, then consider this immediately obsolete... If so, let me know how whether if this ever worked?
=> Fix the regalias file that LRB creates.

Parity/main/QwParity.cc
This is a follow-up of #121 which only stored the blinder status objects when using the QwParity_simple executable.
=> Also store objects in the QwParity executable, not just simple one.

Parity/include/VQwDataHandler.h, Parity/src/VQwDataHandler.cc
This will prepend to the name of leafs in the tree, and should
allow for having multiple correlator sets run simultaneously.
E.g. prefix = kitchensink_ could be everything, while empty
prefix could be the default regression set.
Also works for other data handlers e.g. correctors.
TODO list:
=> Allow for prefix = set1_ flags in data handlers

Analysis/include/QwRootFile.h, Analysis/src/QwRootFile.cc
With `"ppm/D:ppb/D:um/D:mm/D" = { 1e-6, 1e-9, 1e-3, 1 }` one can now
plot things like `mul->Draw("asym_qwk_mdallbars/ppb")` or
`mul->Draw("diff_qwk_xtarg/um")`.
`mul->Print()` indicates that there is hardly an impact on size since
our event size is large and constants compress well. Someone should
evaluate in real-world environment, though.
=> Construct unit branch in every tree

Analysis/include/QwParameterFile.h, Analysis/src/QwParameterFile.cc
In all parsed integer ranges (with ParseIntRange) we now use ParseInt
which also knows about k = 1e3 and M = 1e6. So, now we can do
```
build/qwparity -c prex.conf -r 1296 -e :10k
```
to run the first 10k events. Other options: `-e 1k:` for all events
starting at 1k to end of run. Also works on run ranges, which probably
no one uses.
What doesn't work? 1.5k and the like. Keep it integer.
=> Support for event ranges like `-e :10k`

Parity/src/LRBCorrector.cc, Parity/src/QwCorrelator.cc
This actually causes crashes with gcc-8.3 when a calling function
directly uses the returned value itself in a return. In particular:
```
#include <iostream>
class A {
public:
int f(int i) { return this->f(i,i); };
virtual int f(int,int) { return 0; };
};
class B: public A {
public:
int f(int,int) { /* ERROR HERE */ };
};
int main() {
B* b = new B();
A* a = b;
std::cout << a->f(1) << std::endl;
}
```
when compiled as `g++ -o test -O2 test.cpp` (with warnings!) crashes with
```
Segmentation fault (core dumped)
```
Something a tiny bit more involved happens in japaan. I suspect this is
because of the different behavior of temporaries when returned (constexpr)
since the caller thinks it can evaluate the return value at compile time,
but in practice it fails since there is no temporary to …
=> Return an actual int in functions returning int [-Wreturn-type]

Analysis/include/QwRootFile.h
So, we first check for the directory and use it if it exists. Otherwise we create it and use that one.
This fixes a bug in https://github.com/JeffersonLab/japan/tree/feature-pure-mixin-root-iface which causes the mixin implementation of storing object to not work as intended. With this bugfix it does work as intended. The bugfix is relevant outside the branch too, though, even if we have not run into it.
=> QwRootFile uses TDirectory::mkdir which returns 0 if already exists

Analysis/include/QwRootFile.h, Analysis/src/QwRootFile.cc
If this flag (write-temporary-rootfiles) is false, then we will not create the "unique"
rootfile name by using the machine and process ID in the file name.  This is most useful
to make sure that panguin can find the correct "online" rootfile, by making sure there
is only one file.
=> Added QwRootfile option to disable the use of the "temporary" rootfile.

Analysis/include/QwRootFile.h, Analysis/src/QwRootFile.cc, Parity/prminput/prexCH_beamline.2331-.map, Parity/prminput/prexinj_beamline.2479-.map
Hotfix branched from operations, this brings in a set of parameter file updates, and the ability to disable the production of the temporary rootfile.  The use of disabling the temporary root file is mostly for the "online" engine.
=> Hotfix disable temp rootfile

Analysis/include/QwVQWK_Channel.h, Analysis/src/QwVQWK_Channel.cc
Whereas a running sum may at some point have been part of the channel
we are now using a strategy of keeping running sums entirely outside
the channels so we can have multiple of them at different time scales.
No effects. No hits on `grep -r fRunningSum` (except for things called ...diffRunningSum).
=> Remove QwVQWK_Channel::fRunningSum, not used and confusing

Parity/include/QwCorrelator.h, Parity/prminput/prex_datahandlers.map, Parity/src/QwCorrelator.cc
New options slope-file-base, slope-file-suff to set the name of the
blueR####.new.slope.root file to something else to avoid clobbering.
Default settings (if not specified) are (historically):
```
slope-file-base = blueR
slope-file-suff = new.slope.root
```
=> Specify linregblue correlator output ROOT file name

Analysis/src/QwADC18_Channel.cc, Analysis/src/QwScaler_Channel.cc, Analysis/src/QwVQWK_Channel.cc
... like all decent environments.
This fixes the substring issue which I posted about in slack.
=> TString::First returns -1 when nothing is found instead of npos

Parity/include/QwDataHandlerArray.h, Parity/include/VQwDataHandler.h, Parity/src/QwDataHandlerArray.cc, Parity/src/VQwDataHandler.cc
Since we end up with several lines like:
```
datahandlerarray1.ConstructTreeBranches(rootfile);
datahandlerarray2.ConstructTreeBranches(rootfile);
```
where `datahandlerarray2` is either a copy of or constructed the same was as `datahandlerarray1`, we need a way to distinguishing where their output goes. We can either change the tree name or change the branch names. Examples:
```
datahandlerarray1.ConstructTreeBranches(rootfile,"dh1_");
datahandlerarray2.ConstructTreeBranches(rootfile,"dh2_");
```
will cause trees `dh1_<defaultname>` and `dh2_<defaultname>`.
```
datahandlerarray1.ConstructTreeBranches(rootfile,"","dh1_");
datahandlerarray2.ConstructTreeBranches(rootfile,"","dh2_");
```
will cause one tree `<defaultname>` with branches `dh1_<channel>` and `dh2_<channel>`.
Either way should …
=> Optional tree and branch prefix in data handler ConstructTreeBranches.

Analysis/src/QwVQWK_Channel.cc, Parity/include/QwEventRing.h, Parity/main/QwParity.cc, Parity/src/QwEventRing.cc
At the end of a run we have stuff in the event ring. Although only 200 events, so unlikely to be useful for statistical precision, we don't do anything with these events. This adds the functionality to unwind the event ring (and still not do anything with these events) to test whether problems occur. If the event ring rolling average is non-zero then something fishy happened.
Functionality consists of:
- keeping track of how many events are in the event ring
- printing the rolling average in the event ring
- unwinding after the main event loop
- small fixes in deaccumulation of VQWK channels
=> Feature: Allow event ring to unwind 🏖

Analysis/src/QwADC18_Channel.cc, Analysis/src/QwScaler_Channel.cc, Analysis/src/QwVQWK_Channel.cc
This caused the evts tree in feature-burst-outside-helicitypattern
to not store the correct branch names when saved with "|stat" but
not "yield|stat".
Proposed as PR on develop since it's a bug that could potentially
show up in develop...
=> Bugfix for off by one error on the "|stat" parsing.

Analysis/src/QwScaler_Channel.cc, Analysis/src/QwVQWK_Channel.cc
Since no deaccumulation was present for scalers, they didn't get handled correctly in the event ring. This introduces proper deaccumulation for scaler channels.
=> Bugfix: Improve deaccumulation for VQWK, implement for scalers

Parity/src/QwBeamMod.cc
Most subsystems just pass the prefix on to their channels, but
the beam mod class creates some entries in the tree vector itself.
=> We should chop "|stat" off the tree prefix in beam mod

Analysis/src/QwScaler_Channel.cc, Analysis/src/QwVQWK_Channel.cc, Parity/include/QwClock.h, Parity/include/QwScaler.h, Parity/include/VQwClock.h, Parity/src/QwBeamLine.cc, Parity/src/QwClock.cc, Parity/src/QwHaloMonitor.cc, Parity/src/QwScaler.cc
Builds on PR #176 so merge after that. 
This adds deaccumulation for clocks, scalers, halomonitors
This means that these scalers can now be relied upon for eventring
stability cuts and other types of datahandler alarms.
`build/qwparity -c prex.conf -r 1296 -e :1k --ring.print-after-unwind` now has all zero eventring rolling averages after unwinding.
=> Feature deaccumulate clock halo scalers

Parity/include/QwDataHandlerArray.h, Parity/include/VQwDataHandler.h, Parity/src/QwDataHandlerArray.cc, Parity/src/VQwDataHandler.cc
This was a change that @paulmking and I started implementing last Friday but I can't exactly remember why it was so important that it should have its own branch...
I guess the point was that we are now using things like
```
datahandlerarray_run.AccumulateRunningSum(datahandlerarray);
```
instead of `datahandlerarray_run.AccumulateRunningSum();`
This is part of the burst regression scheme mechanics.
=> Removed fRunningSum from data handlers

Parity/include/QwBlinder.h, Parity/include/QwHelicityPattern.h, Parity/main/QwParity.cc, Parity/src/QwBlinder.cc
Modified blinder functionality to include the framework for random number generated blinder. Now if the Qwparity is run with Online flag, the Blinder will be based on a randomized seed string generated at `QwBlinder::ReadRandomSeed()`. 
In QwParity.cc, 
Load the blinder seed from a random number generator for online mode by checking 
`if (eventbuffer.IsOnline() ){      
helicitypattern.UpdateBlinder();//this routine will call update blinder mechanism using a random number
}else{
//  Load the blinder seed from the database for this runlet.
#ifdef __USE_DATABASE__
helicitypattern.UpdateBlinder(&database);
#endif // __USE_DATABASE__      
}`
Tested the new routine by explicitly calling random number blinding routine at the QwParity. In four runs I see two distinct blinder seeds printed in …
=> Hotfix online blinder

Parity/include/QwCorrelator.h, Parity/src/QwCorrelator.cc
The QwCorrelator class used AccumulateRunningSum() to add events to
the correlation matrices, but that function is now not called anymore.
Instead the class now calls the ProcessData function.
This now prints out the correct correlations and corrected means at the end of the run (1296):
```
Uncorrected Y values:
mean          sig
Y0:  -0.00124514 +- 0.0167122
Y1:  -0.000134772 +- 0.00483523
Y2:  -0.000477551 +- 0.0199558
Y3:  -0.000166495 +- 0.00776414
Y4:  -0.000794472 +- 0.0184763
Y5:  -0.000186235 +- 0.00442468
Y6:  7.88221e-05 +- 0.0173341
Y7:  -0.000256982 +- 0.00752573
Y8:  0.000309415 +- 0.0422519
Y9:  0.000351179 +- 0.018208
Y10:  -0.0013971 +- 0.0677632
Y11:  0.250691 +- 18.9201
Y12:  -0.062942 +- 4.35373
Y13:  0.000499613 +- 1.22973
Y14:  0.716304 +- 53.9539
Y15:  0.456427 +- …
```
=> Bugfix: Use ProcesssData instead of adding events in AccumulateRunningSum (MAJOR)

Tests/go_check.sh, Tests/go_update.sh
Example: `Tests/go_check.sh -r 1296` will run qwparity for 2k events and do a root-diff with the reference root file from develop on hallaweb. `Tests/go_update.sh -r 1296` will update the file on hallaweb (if write permission, if on farm). Go is needed for go_check, not for go_update. Currently only supports run 1296 but easy to add to.
Goal is to do this somewhat automatically on travis (which supports go) but still trying to figure out how do square this with the docker containers we use.
=> Feature: Two test scripts that use root-diff on a reference run on hallaweb

Analysis/src/QwSubsystemArray.cc
Without this initialization some random number is written to the
ROOT tree in both JLab CE and on gcc8 / ROOT 6.16. This causes all
ROOT files to differ every time.
Copy constructor copies values of scandata etc from the source object.
Equally valid, I think, could be to set them to zero again, but unlikely
to make any real difference.
=> Bugfix: Properly initialize scandata1 scandata2 cleandata in ROOT tree (MINOR)

Parity/src/QwSubsystemArrayParity.cc
This ensures that the evt tree contains the correct CodaEventType value. Currently it doesn't get copied out of the event ring and is filled with initial value (or worse, when using -O3, an uninitialized value).
We might have implemented an operator= in QwSubsystemArray instead of only the QwSubsystemArrayParity. Right now we have a compiler defined operator= for QwSubsystemArray which is unpredictable, at best, and wrong at worst.
=> Bugfix: Added CODA event type to the assignment operator= of array (MINOR)

Parity/src/LRBCorrector.cc
Changing the set of regression variables causes LRBCorrector to crash, not anymore.
Trees like mulc_lrb are still filled but with uncorrected values.
=> Bugfix: Make LRBCorrector more robust

Parity/src/QwCorrelator.cc
It was possible to create a QwCorrelator data handler, but not fully
initialize it (e.g. the datahandlerarray_evt which isn't used at all yet
in QwParity doesn't ever call its ConstructTreeBranches method). This
resulted in null TFile pointer which is attempted to close. Result =
segfault on close.
Snuck in two other bug fixes which I thought might be at the cause:
- first close TFile, then delete histograms to make sure they make it
into the file
- only initialize histograms when disable-histos = false in the map file
Verified no segfault on default develop.
=> Hotfix: Only close ROOT file if it has been opened successfully (MAJOR)

Parity/src/QwCorrelator.cc
In particular, don't segfault when the directory LRBoutput is specified (which doesn't exist in the repository). This directory is specified by default as of the recent operations merge.
=> Bugfix: Throw error if QwCorrelator files not writable (e.g. non-existent dir) (MINOR)

Analysis/src/QwRootFile.cc
There is some inconsistency in this naming convention, but the
inconsistency is consistent with the inconsistency between the
disable-hel-tree and mul tree names.
All to save two key strokes... I'm sure we'll publish faster.
=> Feature: Added option --disable-pair-tree to disable pr tree

Parity/src/QwHelicity.cc
This ensures that "diff_|stat" is still treated as a diff_ for the
purpose of histogram/tree filling.
This is a bug fix for enabling pattern and burst histograms and trees,
since the type of histogram filling that is to be done changes between
constuction and filling (due to the use of "|stat"). In general, it may
have been a better idea to not reuse the same flag for histograms and
trees.
=> Bugfix: When checking histogram/tree prefix, allow stuff after diff_ (MINOR)

Analysis/include/QwRootFile.h, Analysis/src/QwRootFile.cc
Require `^mul$` instead of merely `mul` as disable tree name.
These are parsed as regex, and `mul` also matches `mulc` which is not intended. Now `--disable-hel-tree` will only remove the `mul` tree, not the `mulc` tree.
Also implements --disable-tree <regex> for other tree names, e.g. `--disable-tree _lr.\* --disable-tree .\*rst\$`
Escape when using shell wildcards (probably not needed in config files). Composing so options can be repeated.
=> Bugfix: Don't apply disable tree so eagerly (MINOR)

Parity/include/LinReg_Bevington_Pebay.h, Parity/include/QwCorrelator.h, Parity/src/LinReg_Bevington_Pebay.cc, Parity/src/QwCorrelator.cc
Finally figured out how the matrix math expressions for the uncertainties on the slopes:
```
dAxy.Zero();
dAxy.Rank1Update(TMatrixDDiag(invRPP), TMatrixDDiag(mRYYp), norm); // diag mRYYp = row of ones
dAxy.Sqrt();
dAxy.NormByColumn(mSP); // divide
dAxy.NormByRow(mSYp, ""); // mult
```
which is mean square error / ndof * R^-1. TMatrixD is designed for (RPN-like) in-place operations, hence the weird order of operations.
(Really, these were a few loose ends that weren't committed to feature-burst-regression before Paul merged that into develop.)
=> Feature: LRB matrix math

Analysis/src/QwADC18_Channel.cc, Analysis/src/QwVQWK_Channel.cc, Parity/include/QwBlinder.h, Parity/src/QwHelicityPattern.cc
For pairs/patterns that have a blinding failure, blindable asymmetries
will be set to a value of -1 in natural units (1.e. -1000000 ppm)
instead of zero.
Pairs/patterns with a blinding failure will have the ErrorFlag set to
include the blinding error bit instead of just having that appear in
the individual device error codes.
The blindable asymmetries already had their individual error codes
marked in the case of blinding errors, but this now will have the
entire pair/pattern so marked.
=> Changes to how pairs/patterns with blinding errors appear in ROOT files.

Analysis/include/VQwHardwareChannel.h, Analysis/src/VQwHardwareChannel.cc, Parity/src/QwEventRing.cc
This activates another command-line option to set the holdoff period for the burp cuts.  In this version, all burp cuts have the same number of events cut before the failure (precut) and the same number cut cut after the failure (holdoff).
=> Hotfix adjustable burp extent

Analysis/include/QwTypes.h, Parity/include/QwHelicity.h, Parity/src/QwHelicity.cc
This addresses issue #233, in that the helicity error counters now
print correctly.  Along the way, I also modified how the various
counters inside the helicity class propagate through the arithmetic
operators, to behave along the lines of the code introduced in PR#232.
Helicity errors (missed helicity events, sync errors, prediction
errors, etc.) will always cause the 0x20000 bit in ErrorFlag to be set.
=> Allow helicity subsystem to set ErrorFlag and properly print error counters

Analysis/src/QwSubsystemArray.cc, Parity/src/QwSubsystemArrayParity.cc
Propagate CODA event number in +=, -= and accumulators
In particular, try to find the smallest non-zero CODA event number. This means that now
```
mul->Scan("CodaEventNumber")
burst->Scan("CodaEventNumber")
```
all return the right result (curiously even the first one was wrong since it returned the CODA event number of the first POSITIVE helicity event).
Possibly related to #217 in a sense that the reason why mps_counter is set to the value at the first positive helicity windows is the same as here. We only set some variables when we execute operator=. The order of operations for helicity pattern quantities is operator= on first positive helicity, operator+= on all the next, then operator= on the first negative, operator+= on all the next, then Sum, Difference on the positive and …
=> Bugfix: Correct coda event number in burst (MINOR)

Parity/include/LRBCorrector.h, Parity/include/QwCorrelator.h, Parity/include/VQwDataHandler.h, Parity/main/QwParity.cc, Parity/src/LinReg_Bevington_Pebay.cc, Parity/src/QwCorrelator.cc, Parity/src/QwDataHandlerArray.cc, Parity/src/VQwDataHandler.cc
The correlator now has a cycle counter that increments each time
we write a set of outputs.  This is independent of the burst
counter, but for the "burst correlator" does increment when the
burst counter does.
The VQwDataHandler error flag pointer gets assigned at the same
time as the source pointer.
VQwDataHandler contains its own running sum; this provides some
consistency in behavior between the correlator and other data handlers,
although it is inconsistent with how running sums work for the
subsystem arrays and pattern object.
=> Getting the running sum calculation for the data handlers to work.

Parity/src/QwHelicityPattern.cc
Updating burst definition to only increment the burst after N good patterns.
This needs to have an optional flag added to it to allow for the original N patterns (regardless of good) too.
This works: 
Bursts are 9k long (as desired)
Bursts are variable in length to include the right number of good patterns
Here's what it was before, when the "good" pattern was only based on the analyzer's ability to actually create a pattern (without checking the internal data quality).
=> Updating burst definition to only increment the burst after N good patterns

Parity/src/QwHelicityPattern.cc
Added the fPatternSize variable to the copy constructor for QwHelicityPattern. There is still the possible frailty since it relies on "bcm_an_us" being a good variable to monitor good events. Considering a parameter to run range the name of the good current monitor (as far as i recall, this was changing over the course of PREX). That will be a robust fix. But this should work for now.
=> Fixes the issue with number of good events.

Parity/include/QwHelicityPattern.h, Parity/main/QwParity.cc, Parity/src/QwHelicityPattern.cc
So far it just lets the user specify from the command line.
Want to have a max-burst-index conf file printer function (probably triggered by a command line option as well) for a hypothetical 0.5 pass initial run to give N bursts - 1 as output for a proper 1st pass to have the correct number of bursts in it (be careful that this doesn't persist into future respins, as cuts can change the amount of good data in a run independently of pass 0.5, 1, 2, etc.).
Want to have a numerical-merging of N and N-1 bursts slope outputs so that they can be used from the 0.5 pass directly onto 2nd pass outputs (saving an entire 1st pass root file printing procedure and only pushing fully corrected data 5 minutes down the line).
=> Adding a 0.5->1 pass final burst length feature

Parity/include/QwBlinder.h, Parity/prminput/blinder.5104-5274.map, Parity/prminput/blinder.5275-.map, Parity/src/QwBlinder.cc
This extends the mechanic that we used to differentiate between the PREX and
CREX taret position ranges to allow more than two sets of blindable target
ranges.
The PREX positions are associated to target index "-1", and the CREX positions
to date are index "1".  The new CREX target encoder position will be "2", and we
can easily define more later if needed (like if the encoder changes).
=> Hotfix to allow selecting run-dependent blindable target positions.

Parity/prminput/prexCH_beamline_eventcuts.2948-.map, Parity/prminput/prexCH_beamline_eventcuts.3139.map, Parity/prminput/prexCH_beamline_eventcuts.3289-3292.map, Parity/prminput/prexCH_beamline_eventcuts.3403.map, Parity/prminput/prexCH_beamline_eventcuts.3404-.map, Parity/prminput/prexCH_beamline_eventcuts.3425-3428.map, Parity/prminput/prexCH_beamline_eventcuts.3450-3452.map, Parity/prminput/prexCH_beamline_eventcuts.3455.map, Parity/prminput/prexCH_beamline_eventcuts.3489.map, Parity/prminput/prexCH_beamline_eventcuts.3524.map, Parity/prminput/prexCH_beamline_eventcuts.3540.map
make sure bpm 4a, 4e and 12 appear in all beamline_eventcuts map files,
and 11 doesn't appears in map files before
prexCH_beamline_eventcuts.3403.map (included) and appears
in all map files after prexCH_beamline_eventcuts.3404-.map (included)
=> Modify bpm setting in some beamline_eventcuts map files

Parity/prminput/prexCH_beamline_eventcuts.3390-.map, Parity/prminput/prexCH_beamline_eventcuts.3403.map
BPM 11 wire cut was missing from 3403.
Also, runs before 3912 lack BPM burp cuts, but the "good" cut diagnostics we saw during prompt running depended on the old version of the analyzer. So, it is worth checking if the burp cuts from 3912-> should be added to <-3912 runs.
We will also want to make sure the event cuts match the BCM normalizer (once Paul fixes that up), which will be its own ordeal of editing map files.
Other than these points everything looks fine for PREX maps, other than the quite large number of maps and our unfortunately frequent use of single-run event cut files for cleaning up noisy beam.
=> Cuts for PREX respin cleanup

Parity/prminput/prex_corrolator.3088.conf, Parity/prminput/prex_corrolator.3089-.conf, Parity/prminput/prex_corrolator.3130-.conf, Parity/prminput/prex_corrolator.3583-.conf, Parity/prminput/prex_corrolator.3803-.conf, Parity/prminput/prex_corrolator.3884-3893.conf, Parity/prminput/prex_corrolator.4708-4939.conf, Parity/prminput/prex_corrolator_all.3130-3389.conf, Parity/prminput/prex_corrolator_all.3390-.conf, Parity/prminput/prex_corrolator_all.3803-.conf, Parity/prminput/prex_corrolator_all.3884-3893.conf, Parity/prminput/prex_corrolator_all.4708-4939.conf, Parity/prminput/prex_corrolator_alldet.3130-.conf, Parity/prminput/prex_corrolator_alldet.3390-.conf, Parity/prminput/prex_corrolator_alldet.3583-.conf, Parity/prminput/prex_corrolator_alldet.3803-.conf, Parity/prminput/prex_corrolator_alldet.3884-3893.conf, Parity/prminput/prex_corrolator_alldet.4708-4939.conf, Parity/prminput/prex_maindet_eventcuts.3803-.map, Parity/prminput/prex_maindet_eventcuts.3884-3893.map, Parity/prminput/prex_maindet_eventcuts.4074-4077.map, Parity/prminput/prex_maindet_eventcuts.4679-4690.map
Start caring about ATs, prior runs are often saturated - prex_maindet_eventcuts.3803-.map
Left arm only running - prex_maindet_eventcuts.3884-3893.map
Left arm only running - prex_maindet_eventcuts.4074-4077.map
Left arm only running - prex_maindet_eventcuts.4679-4690.map
ATs hardware blinded  - prex_maindet_eventcuts.4708-4939.map
All per Devi
=> Updating global event cuts for PREX respin 2 to include AT detectors

Parity/src/QwBlindDetectorArray.cc, Parity/src/QwCombiner.cc, Parity/src/QwCorrelator.cc, Parity/src/QwDetectorArray.cc
Resolves a bug that data handlers are not able to request IV's from previously defined data handlers (DV's had been request-able already), and removes extraneous error messages during the data element request process for the detector array classes.
This will resolve issues #296 and #271 for the develop branch.
=> Bugfix datahandlers fail connecting ivs

Parity/prminput/prex_datahandlers.2948-2962.map, Parity/prminput/prex_datahandlers.3130-4980.map, Parity/prminput/prex_datahandlers.5140-.map
The "BMW extractor" had not been included in the standard data hanlder configurations
for much of the PREX and CREX run periods.  It had been present in the last portion
of the CREX run period already.
=> Adding the "BMW extractor" to the standard PREX/CREX data handler arrays

Parity/prminput/prex_bad_events.4512.map, Parity/prminput/prex_bad_events.4519.map
One event in each of runs 4512 and 4519 has the analog US bcm signal
glitch low by about 20uA.  The DS analog bcm remains in agreement with
the two digital bcm signals for these two events.
These events have been marked as bad.
=> Cut one event in each of runs 4512 and 4519.

Analysis/src/QwOptions.cc, Parity/include/QwBlinder.h, Parity/src/LRBCorrector.cc, evio/include/THaCodaFile.h, evio/src/THaCodaFile.C
`0x80730001` is an unsigned int. Comparing to an int requires conversion to an int, which narrows the domain. In this case, `staterr` is a harmless function that only provides helpful warning messages. We change the status variable into an unsigned int so that the conversion is made explicit in the call to `staterr`.
```
[  1%] Building CXX object evio/CMakeFiles/evio.dir/src/THaCodaFile.C.o
cd /home/wdconinc/git/japan/build/evio && /usr/bin/c++  -Devio_EXPORTS -I/home/wdconinc/git/japan/evio/include -I/home/wdconinc/git/japan/build/evio -isystem /usr/local/root/pro/include  -O2 -g -DNDEBUG -fno-omit-frame-pointer -fPIC   -pipe -fsigned-char -mtune=generic -pthread -std=c++17 -m64 -Wall -o CMakeFiles/evio.dir/src/THaCodaFile.C.o -c /home/wdconinc/git/japan/evio/src/THaCodaFile.C
In file …
```
=> Bugfix: avoid evio narrowing warning/error on gcc-10 (after #313)

Parity/src/LinReg_Bevington_Pebay.cc
This has been test compiled with ROOT 6.24.00  and g++ 7.5.0 on Ubuntu 18.04.5
=> Adding include of TString.h needed to compile with ROOT newer than 6.20.

Parity/include/QwBPMCavity.h, Parity/include/QwBPMStripline.h, Parity/include/QwCombinedBPM.h, Parity/include/QwQPD.h, Parity/include/QwUtil.h, evio/src/THaCodaFile.C
- THaCodaFile switch variable was out of range
- Several constructors attempted direct initialization of C-style arrays, array(other.array), which is ill-formed C++. (How did this ever work?)
Fixes JeffersonLab/japan#2
=> Fix compilation on macOS (and probably on other platforms too)
