- Analysis/include/QwEventBuffer.h
- Analysis/include/QwScaler_Channel.h
- Analysis/src/QwEventBuffer.cc
- Analysis/src/QwScaler_Channel.cc
- Parity/include/QwHelicity.h
- Parity/main/QwParity.cc
- Parity/prminput/parity_hist.in
- Parity/prminput/prex.conf
- Parity/prminput/prexCH_beamline.4747-.map
- Parity/prminput/prexCH_detectors.map
- Parity/prminput/prexCH_helicity.4747-.map
- Parity/prminput/prexCH_helicity.map
- Parity/prminput/prex_detectors.map
- Parity/prminput/prexbankflag.4747-.conf
- Parity/prminput/prexbankflag.conf
- Parity/prminput/prexinj.conf
- Parity/prminput/prexinj_beamline.4747-.map
- Parity/prminput/prexinj_helicity.4100-.map
- Parity/prminput/prexinj_helicity.4747-.map
- Parity/src/QwHelicity.cc
Changes in the event buffer handling to support decoding of the counting house helicity signals, and to support the Hall A sub-bank structures.
> Feature: Decode counting house A helicity signals

- .travis.yml
- Dockerfile
This works as per checkmark at https://github.com/JeffersonLab/japan/branches :-) Also, docker image at https://hub.docker.com/r/jeffersonlab/japan/.
> Integrate Travis CI into develop

- Analysis/include/QwRootFile.h
- Analysis/src/QwRootFile.cc
- Parity/prminput/online_apar.conf
- Parity/prminput/tree_trim.in
- panguin/CMakeLists.txt
- panguin/README.md
- panguin/include/panguinOnline.hh
- panguin/macros/defaultOnline.cfg
- panguin/src/panguinOnlineConfig.cc
This should work now. The scheme is to write the file on the disk -- with an ~1h circular tree --, have the trees autosaved every X number of events (see the conf file) and have panguin monitor the file and make plots. In the process I updated how panguin finds rootfiles in the QW_ROOTFILES folder.
The only issue that I see is that the drawing gets a bit funky when it updates. As far as I can tell this is not related to the monitoring functionality (will investigate sometime next week).
> Feature online panguin

- panguin/README.md
- panguin/include/panguinOnline.hh
- panguin/include/panguinOnlineConfig.hh
- panguin/panguin.cc
- panguin/src/panguinOnline.cc
- panguin/src/panguinOnlineConfig.cc
This should fix the histogram titles.
Additionally I added a timer to panguin to print out how long different things take and introduced a verbosity variable for easier future debugging.
> Hotfix histo titles

- rootScripts/aggregator/README.md
- rootScripts/aggregator/anaInt.cfg
- rootScripts/aggregator/analyze.cfg
- rootScripts/aggregator/camAna.hh
- rootScripts/aggregator/camHist.hh
- rootScripts/aggregator/camIO.hh
- rootScripts/aggregator/camguin.C
- rootScripts/aggregator/camguin.hh
- rootScripts/aggregator/default.cfg
- rootScripts/aggregator/panguin_wrapper.sh
- rootScripts/aggregator/setup_camguin.tcsh
Aggregate Monitor for PANGUIN (CAMGUIN).
It can be turned into separate macros (I already wrote them elsewhere but they lagged behind development of the .hh versions), and I am planning to rewrite it as a compiled executable or as an addition into PANGUIN's classes itself with actual object behavior and inheritance to remove superfluous method calls (i.e. for finding the ROOT file/tree/branc/runnumber/etc.)
> Adding a macro-based version of the Continuous

- Analysis/include/QwPromptSummary.h
- Analysis/src/QwPromptSummary.cc
- Parity/include/QwBeamLine.h
- Parity/include/QwDetectorArray.h
- Parity/include/VQwBPM.h
- Parity/src/QwBeamLine.cc
- Parity/src/QwBlindDetectorArray.cc
- Parity/src/QwDetectorArray.cc
This modifies the old QwAnalysis prompt summary system to work with the PREX channels.
> Feature promptsummary

- rootScripts/aggregator/README.md
- rootScripts/aggregator/camAna.hh
- rootScripts/aggregator/camHist.hh
- rootScripts/aggregator/camIO.hh
- rootScripts/aggregator/camguin.C
- rootScripts/aggregator/postPan.cfg
- rootScripts/aggregator/postpan_wrapper.sh
are hardcoded, like assuming the .txt files are in a folder
called txt_out, and this should change. This works for the
.txt files as of 4/8/2019 but any change will break it).
> Adding postpan .txt file reading methods (some things

- Parity/src/LinReg_Bevington_Pebay.cc
> Hotfix in LinReg

- Analysis/include/QwPromptSummary.h
- Analysis/src/QwPromptSummary.cc
- Parity/include/QwBeamLine.h
- Parity/include/QwDataHandlerArray.h
- Parity/include/QwDetectorArray.h
- Parity/include/VQwDataHandler.h
- Parity/main/QwParity.cc
- Parity/prminput/prex_combiner.map
- Parity/prminput/prex_respin2.conf
- Parity/src/LRBCorrector.cc
- Parity/src/QwBeamLine.cc
- Parity/src/QwBlindDetectorArray.cc
- Parity/src/QwCombiner.cc
- Parity/src/QwDataHandlerArray.cc
- Parity/src/QwDetectorArray.cc
- Parity/src/VQwDataHandler.cc
The prompt summary is now able to pull information from the data handler classes, such as double differences and average asymmetries.
The formatting of the prompt summary output has been modifed.
> Feature prompt summary

- Parity/include/QwBPMStripline.h
- Parity/include/VQwBPM.h
- Parity/src/QwBPMStripline.cc
- Parity/src/VQwBPM.cc
Elli = xp+xm-yp-ym/xp+xm+yp+ym and there should be
a scale factor but I don't know what it is.
This begins to resolve issue #14
> Adding ellipticity computed variable to output

- Parity/include/VQwDataHandler.h
- Parity/src/VQwDataHandler.cc
The fRunningSum was with lower case 'sum' while the corresponding boolean was with upper case 'Sum' leading to confusion :-)
> [Minor] Renaming fRunningsum to fRunningSum in VQwDataHandler

- rootScripts/aggregator/CMakeLists.txt
- rootScripts/aggregator/camAna.hh
- rootScripts/aggregator/camHist.hh
- rootScripts/aggregator/camIO.hh
- rootScripts/aggregator/camguin.C
- rootScripts/aggregator/camguin.hh
- rootScripts/aggregator/camguin_compile.C
- rootScripts/aggregator/regressor/camReg.hh
- rootScripts/aggregator/regressor/camRegDipole.hh
- rootScripts/aggregator/setup_camguin.tcsh
Updating some stuff, this is only affecting camguin/aggregator scripts.
> Feature cam alarm

- Parity/include/LRBCorrector.h
- Parity/prminput/prex_datahandlers.map
- Parity/src/LRBCorrector.cc
- Parity/src/LinReg_Bevington_Pebay.cc
This is the math edits branch. it also includes a change to LRBcorrector to read variables from the tree.
> Separated matrix math edits from event handler. 

- panguin/README.md
- panguin/include/panguinOnline.hh
- panguin/macros/online_INJ.cfg
- panguin/src/panguinOnline.cc
- panguin/src/panguinOnlineConfig.cc
It will show current time, plots last updated time and root file last updated time.
Current time will be update second wise;
Plots and file updated time will be updated when plots are refresh.
> new heartbeat feature

- Parity/include/QwBPMCavity.h
- Parity/prminput/prexCH_beamline.1194-.map
- Parity/prminput/prexCH_beamline.1199-.map
- Parity/prminput/prexCH_beamline.1283-1396.map
- Parity/prminput/prexCH_beamline.1284.map
- Parity/prminput/prexCH_beamline.1336-1348.map
- Parity/prminput/prexCH_beamline.1397-1420.map
- Parity/prminput/prexCH_beamline.1449-1450.map
- Parity/prminput/prexCH_beamline.map
- Parity/prminput/prexCH_beamline_pedestal.1224-1236.map
- Parity/prminput/prex_corrolator.conf
- Parity/src/QwBPMCavity.cc
- Parity/src/QwBeamDetectorID.cc
- Parity/src/QwBeamLine.cc
- rootScripts/pedestal/cavityBPMPedestalMacro.C
Updating the cavity BPM class for PREX
> Feature cavity bpm

- Parity/include/QwAlarmHandler.h
- Parity/include/QwSubsystemArrayParity.h
- Parity/include/VQwDataHandler.h
- Parity/prminput/prex_alarm_handler.map
- Parity/prminput/prex_datahandlers.map
- Parity/src/QwAlarmHandler.cc
- Parity/src/VQwDataHandler.cc
This update adds a new alarm handler modeled after the convincer. It will need more edits to be prettier and more intuitive, but it is entirely functional as it stands
> Feature add alarm handler

- Analysis/src/QwADC18_Channel.cc
Minor fix in just the comments.
> ADC18 claims to be a scaler in FillTreeVector.

- Parity/include/QwEventRing.h
- Parity/src/QwEventRing.cc
> Added beam trip holdoff

- Parity/prminput/prexCH_beamline_eventcuts.2353-.map
- Parity/src/QwBeamLine.cc
The Cavity BPMs were moved from the BCM array to their own array. So, QwBeamLine.cc needed to be modified. 
Also the bcm_an_ds3 event cut was only set to local. Changed that to global.
> Feature promptsummaryaddcavity

- Parity/src/QwHelicityPattern.cc
Just changing the default value.
> Feature: Change default burst length to 9000 patterns

- SetupFiles/make_scratch_dir
> Bugfix: make_scratch_dir a tcsh script, not a bash script (MINOR)

- Parity/prminput/prex_corrolator.conf
Will crash lrb corrector runs when a blueR file is already present...
> Feature: Add bcm12x to correlation set

- rootScripts/correlator/CompareBlockToHwSum.C
- rootScripts/correlator/PlotByBlock.C
> Feature: Two analysis scripts for subblock to hw_sum correlation comparison

- Parity/prminput/prex_corrolator.2928-.conf
- Parity/prminput/prex_corrolator.conf
- Parity/prminput/prex_corrolator_all.conf
- Parity/src/QwCorrelator.cc
Also add offending key in future error messages.
> Comment unused correlator map lines, remove red error messages

- Analysis/include/QwSubsystemArray.h
- Analysis/src/QwSubsystemArray.cc
- Parity/include/QwSubsystemArrayParity.h
- Parity/src/QwSubsystemArrayParity.cc
This assignment operator is now called by the QwSubsystemArrayParity assignment operator.
Tested by checking that correlation slopes are unchanged (assuming that's a sufficiently high level test to ensure that subsystem arrays are correctly assigned).
> Bugfix: issue 200, QwSubsystemArray operator= implemented

- Parity/include/LinReg_Bevington_Pebay.h
- Parity/include/QwCorrelator.h
- Parity/include/VQwDataHandler.h
- Parity/src/LinReg_Bevington_Pebay.cc
- Parity/src/QwCorrelator.cc
- Parity/src/QwDataHandlerArray.cc
This cleans up the LRB matrix math quite a bit, and removes the unused testval warnings. It also makes LRB objects accumulate-able. Last bit of work before burst regression.
> Feature: LRB using TMatrixD math

- Parity/prminput/prexCH_beamline_pedestal.2956-.map
- rootScripts/pedestal/cavityBPMPedestalMacro.C
Merging of the "high current" cavity BPM calibration work which had been done by M. Vallee.
> Feature cavity bpm calibration

- Analysis/include/QwTypes.h
- Parity/src/QwHelicity.cc
> Hotfix stability cut

- Parity/prminput/prex_combiner.3390-.map
- Parity/prminput/prex_combiner.3803-.map
- Parity/prminput/prex_combiner.map
diff_bpm4aesumY,X:
bpm4eY+-0.65*bpm4aY
-+bpm4aX+0.18*bpm4eX
> Updating combiner to have target BPM combos for dithering:

- Parity/prminput/prexCH_beamline.7502-.map
Map file change:  swapped tsettle and beam_mod_ramp cable channels  in VQWEAK 5 (channel 3 is broken; tsettle no longer working)
> Update counting house channel map for BMod Ramp
